### ISSUE TITLE
Visitors Today showing same visitor multiple times

### ISSUE THREAD

**Issue by cp-nilly** [NicolasSiver/nodebb-widget-ns-stats#1]
Not sure if this is intended behavior. If it is, it would be nice to have an option to only display the set of users that had visited during the day rather than the occurrence of users throughout the day.

**Comment by NicolasSiver** [comment]
Basically, It has to be a unique list.
Could you provide screenshot of this problem from your board?

**Comment by cp-nilly** [comment]
![](http://i.imgur.com/ifwlAjM.png)

Perhaps server resets/restarts have something to do with it?

**Comment by NicolasSiver** [comment]
Interesting. I think there is a problem in caching algorithm for Visitors.
Don't know why It's not reproduced on my board. 
Yes, cache is used on restarts.
Do you use `mongo` or `redis`?

**Comment by cp-nilly** [comment]
Redis.

**Comment by NicolasSiver** [comment]
Don't hesitate to share your experience. Did it fix it your problem with visitors list.
I don't have this problem even with restarts. But i'm using MongoDB.
I have added a very small change.

**Comment by cp-nilly** [comment]
Thanks for giving this issue some attention. I've updated the plugin and it appears as if the problem has went away. A few hours now and no duplicates. :)
